#!/bin/csh -efx
# This script was automatically generated by /cluster/bin/scripts/doCpgIslands.pl
# It is to be executed on ku in /hive/data/inside/ncbi/genomes/genbank/bacteria/Mycobacterium_marinum/latest_assembly_versions/GCA_000018345.1_ASM1834v1/cpg .
# Run /scratch/data/cpgIslandExt/cpglh on masked sequence.
# This script will fail if any of its commands fail.

cd /hive/data/inside/ncbi/genomes/genbank/bacteria/Mycobacterium_marinum/latest_assembly_versions/GCA_000018345.1_ASM1834v1/cpg

mkdir -p results
chmod a+x runCpg.csh
rm -f file.list
find ./hardMaskedFa -type f > file.list
/parasol/bin/gensub2 file.list single gsub jobList
/parasol/bin/para make jobList
/parasol/bin/para check
/parasol/bin/para time > run.time
cat run.time
