#!/bin/bash
# This script was automatically generated by /cluster/bin/scripts/doCpgIslands.pl
# It is to be executed on hgwdev in /hive/data/inside/ncbi/genomes/genbank/bacteria/Mycobacterium_marinum/latest_assembly_versions/GCA_000018345.1_ASM1834v1/cpg .
# Constructs hardMaskedFa/*.2bit files for processing with cphlh.
# This script will fail if any of its commands fail.
# fail on any error:
set -xbeEu -o pipefail

cd /hive/data/inside/ncbi/genomes/genbank/bacteria/Mycobacterium_marinum/latest_assembly_versions/GCA_000018345.1_ASM1834v1/cpg

rm -fr parts hardMaskedFa
mkdir hardMaskedFa
export twoBit="/hive/data/inside/ncbi/genomes/genbank/bacteria/Mycobacterium_marinum/latest_assembly_versions/GCA_000018345.1_ASM1834v1/GCA_000018345.1_ASM1834v1.ncbi.2bit"
export maxSize=`sort -k2nr /hive/data/inside/ncbi/genomes/genbank/bacteria/Mycobacterium_marinum/latest_assembly_versions/GCA_000018345.1_ASM1834v1/GCA_000018345.1_ASM1834v1.ncbi.chrom.sizes | head -1 | awk '{print $2}'`
/cluster/bin/scripts/partitionSequence.pl -lstDir parts $maxSize 0 $twoBit /hive/data/inside/ncbi/genomes/genbank/bacteria/Mycobacterium_marinum/latest_assembly_versions/GCA_000018345.1_ASM1834v1/GCA_000018345.1_ASM1834v1.ncbi.chrom.sizes 30 > /dev/null
for L in parts/part*.lst
do
  B=`basename $L | sed -e 's/.lst//;'`
  sed -e 's/.*.2bit://; s/:0-.*//;' ${L} > ${B}.list
  twoBitToFa -seqList=$B.list ${twoBit} stdout | maskOutFa stdin hard stdout \
     | faToTwoBit stdin hardMaskedFa/$B.t.2bit
  rm -f ${B}.list
  twoBitToFa hardMaskedFa/$B.t.2bit stdout | faCount stdin | egrep -v "^total|^#seq" | awk '$2-$7 > 200 { printf "%s\n", $1}' > $B.list
  if [ -s $B.list ]; then
    twoBitToFa -seqList=$B.list hardMaskedFa/$B.t.2bit stdout | faToTwoBit stdin hardMaskedFa/$B.2bit
  fi
  rm -f hardMaskedFa/$B.t.2bit $B.list
done
date > hardMask.done
