#!/bin/csh -efx
# This script was automatically generated by /cluster/bin/scripts/doCpgIslands.pl
# It is to be executed on hgwdev in /hive/data/inside/ncbi/genomes/genbank/bacteria/Mycobacterium_marinum/latest_assembly_versions/GCA_000018345.1_ASM1834v1/cpgU .
# Makes bed from cpglh output.
# This script will fail if any of its commands fail.

cd /hive/data/inside/ncbi/genomes/genbank/bacteria/Mycobacterium_marinum/latest_assembly_versions/GCA_000018345.1_ASM1834v1/cpgU

catDir -r results \
     | awk '{$2 = $2 - 1; width = $3 - $2;  printf("%s\t%d\t%s\t%s %s\t%s\t%s\t%0.0f\t%0.1f\t%s\t%s\n", $1, $2, $3, $5, $6, width, $6, width*$7*0.01, 100.0*2*$6/width, $7, $9);}' \
     | sort -k1,1 -k2,2n > cpgIsland.bed
bedToBigBed -tab -type=bed4+6 -as=$HOME/kent/src/hg/lib/cpgIslandExt.as \
  cpgIsland.bed /hive/data/inside/ncbi/genomes/genbank/bacteria/Mycobacterium_marinum/latest_assembly_versions/GCA_000018345.1_ASM1834v1/GCA_000018345.1_ASM1834v1.ncbi.chrom.sizes GCA_000018345.1_ASM1834v1.cpgIslandExtUnmasked.ncbi.bb
